sudo docker rmi strg/ts-train-service:latest
sudo docker rmi strg/ts-ui-dashboard:latest
sudo docker rmi strg/ts-auth-service:latest
sudo docker rmi strg/ts-user-service:latest
sudo docker rmi strg/ts-verification-code-service:latest
sudo docker rmi strg/ts-contacts-service:latest
sudo docker rmi strg/ts-order-service:latest
sudo docker rmi strg/ts-order-other-service:latest
sudo docker rmi strg/ts-config-service:latest
sudo docker rmi strg/ts-station-service:latest
sudo docker rmi strg/ts-travel-service:latest
sudo docker rmi strg/ts-travel2-service:latest
sudo docker rmi strg/ts-preserve-service:latest
sudo docker rmi strg/ts-preserve-other-service:latest
sudo docker rmi strg/ts-basic-service:latest
sudo docker rmi strg/ts-ticketinfo-service:latest
sudo docker rmi strg/ts-price-service:latest
sudo docker rmi strg/ts-notification-service:latest
sudo docker rmi strg/ts-security-service:latest
sudo docker rmi strg/ts-inside-payment-service:latest
sudo docker rmi strg/ts-execute-service:latest
sudo docker rmi strg/ts-payment-service:latest
sudo docker rmi strg/ts-rebook-service:latest
sudo docker rmi strg/ts-cancel-service:latest
sudo docker rmi strg/ts-route-service:latest
sudo docker rmi strg/ts-assurance-service:latest
sudo docker rmi strg/ts-seat-service:latest
sudo docker rmi strg/ts-travel-plan-service:latest
sudo docker rmi strg/ts-route-plan-service:latest
sudo docker rmi strg/ts-food-map-service:latest
sudo docker rmi strg/ts-food-service:latest
sudo docker rmi strg/ts-consign-price-service:latest
sudo docker rmi strg/ts-consign-service:latest
sudo docker rmi strg/ts-admin-order-service:latest
sudo docker rmi strg/ts-admin-basic-info-service:latest
sudo docker rmi strg/ts-admin-route-service:latest
sudo docker rmi strg/ts-admin-travel-service:latest
sudo docker rmi strg/ts-admin-user-service:latest
sudo docker rmi strg/ts-news-service:latest
sudo docker rmi strg/ts-ticket-office-service:latest
sudo docker rmi strg/ts-voucher-service:latest

sudo docker rmi ts/ts-train-service:latest
sudo docker rmi ts/ts-ui-dashboard:latest
sudo docker rmi ts/ts-auth-service:latest
sudo docker rmi ts/ts-user-service:latest
sudo docker rmi ts/ts-verification-code-service:latest
sudo docker rmi ts/ts-contacts-service:latest
sudo docker rmi ts/ts-order-service:latest
sudo docker rmi ts/ts-order-other-service:latest
sudo docker rmi ts/ts-config-service:latest
sudo docker rmi ts/ts-station-service:latest
sudo docker rmi ts/ts-travel-service:latest
sudo docker rmi ts/ts-travel2-service:latest
sudo docker rmi ts/ts-preserve-service:latest
sudo docker rmi ts/ts-preserve-other-service:latest
sudo docker rmi ts/ts-basic-service:latest
sudo docker rmi ts/ts-ticketinfo-service:latest
sudo docker rmi ts/ts-price-service:latest
sudo docker rmi ts/ts-notification-service:latest
sudo docker rmi ts/ts-security-service:latest
sudo docker rmi ts/ts-inside-payment-service:latest
sudo docker rmi ts/ts-execute-service:latest
sudo docker rmi ts/ts-payment-service:latest
sudo docker rmi ts/ts-rebook-service:latest
sudo docker rmi ts/ts-cancel-service:latest
sudo docker rmi ts/ts-route-service:latest
sudo docker rmi ts/ts-assurance-service:latest
sudo docker rmi ts/ts-seat-service:latest
sudo docker rmi ts/ts-travel-plan-service:latest
sudo docker rmi ts/ts-route-plan-service:latest
sudo docker rmi ts/ts-food-map-service:latest
sudo docker rmi ts/ts-food-service:latest
sudo docker rmi ts/ts-consign-price-service:latest
sudo docker rmi ts/ts-consign-service:latest
sudo docker rmi ts/ts-admin-order-service:latest
sudo docker rmi ts/ts-admin-basic-info-service:latest
sudo docker rmi ts/ts-admin-route-service:latest
sudo docker rmi ts/ts-admin-travel-service:latest
sudo docker rmi ts/ts-admin-user-service:latest
sudo docker rmi ts/ts-news-service:latest
sudo docker rmi ts/ts-ticket-office-service:latest
sudo docker rmi ts/ts-voucher-service:latest

sudo docker rmi $(docker image ls -qf dangling=true)
sudo docker image prune -f